import Head from "next/head";
import DataTable from "../components/DataTable";
import Header from "../components/Header";
import Sensors from "../components/Sensors";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Sensors />
      <DataTable />
    </div>
  );
}
